permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: dunyi xu
  email: dunyixu@gmail.com
  link: http://dyxu.github.io
  weibo: http://weibo.com/dunyixu
  github: http://github.com/dyxu
  twitter: https://twitter.com/dunyixu
# linkedin: 

# 站点信息
title: dunyi的博客
description: My personal blog
url: http://painterlin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-72595872-1
  url: dyxu.github.io

# disqus 设置
disqus:
  shortname: dyxu

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - 工具
  - 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档